spring.application.name=MedTracker
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
spring.datasource.url=jdbc:postgresql://localhost:5432/medtracker_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
slack.bot-token=
slack.signing-secret=
app.frontend.url=http://127.0.0.1:3000
jwt.secret=medtracker-dev-secret-key-medtracker-dev-secret-key
jwt.expiration-ms=86400000
